# Generated by Django 5.1 on 2024-08-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0002_alter_project_description_alter_project_html_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=1000)),
                ('message', models.TextField()),
            ],
        ),
    ]
