# Generated by Django 5.1 on 2024-08-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0004_alter_contact_email_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='html_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='FRONTCONECT_email_5c25ea_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title', 'html_url'], name='FRONTCONECT_title_2636d8_idx'),
        ),
    ]
