# Generated by Django 5.1 on 2024-08-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0006_alter_contact_message_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='html_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
