# Generated by Django 5.1 on 2024-08-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0009_alter_project_html_url_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='html_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
