# Generated by Django 5.1 on 2024-08-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0010_alter_project_html_url_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='checker',
            field=models.BooleanField(default=False),
        ),
    ]
