# Generated by Django 5.1 on 2024-08-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0011_project_checker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='checker',
        ),
    ]
