# Generated by Django 5.1 on 2024-08-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0014_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
