# Generated by Django 5.1 on 2024-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0015_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='html_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
