# Generated by Django 5.1 on 2024-08-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0017_alter_project_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
