# Generated by Django 5.1 on 2024-08-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0018_contact_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='country_code',
        ),
    ]
