# Generated by Django 5.1 on 2024-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0019_remove_contact_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='corosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('html_url', models.URLField(max_length=1000)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='FRONTCONECT_title_8c0803_idx')],
            },
        ),
    ]
