# Generated by Django 5.1 on 2024-08-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0020_corosel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
