# Generated by Django 5.1 on 2024-08-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0021_alter_corosel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
