# Generated by Django 5.1 on 2024-08-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0022_alter_corosel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
