# Generated by Django 5.1 on 2024-08-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0023_alter_corosel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
