# Generated by Django 5.1 on 2024-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0024_alter_corosel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='media/images/posts/')),
                ('html_url', models.URLField(max_length=1000)),
            ],
        ),
    ]
