# Generated by Django 5.1 on 2024-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0026_alter_posts_description_alter_posts_html_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
