# Generated by Django 5.1 on 2024-08-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0028_alter_posts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='html_url',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
