# Generated by Django 5.1 on 2024-08-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0029_alter_posts_html_url_alter_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corosel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
