# Generated by Django 5.1 on 2024-08-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0030_alter_corosel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(null=True)),
                ('website', models.URLField(max_length=1000)),
                ('image', models.ImageField(upload_to='seviceimg/')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='FRONTCONECT_title_52c398_idx')],
            },
        ),
    ]
