# Generated by Django 5.1 on 2024-08-18 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRONTCONECTION', '0031_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='services_des',
        ),
        migrations.RenameIndex(
            model_name='services_des',
            new_name='FRONTCONECT_title_8e8a1f_idx',
            old_name='FRONTCONECT_title_52c398_idx',
        ),
    ]
